import type { Platform } from "./types";
import { YouTubePlatform } from "./youtube";

export const PLATFORMS: Platform[] = [
  YouTubePlatform,
  {
    id: "instagram",
    name: "Instagram",
    type: "link",
    icon: "instagram",
    placeholder: "Paste Instagram Reel link...",
    buttonLabel: "Summarize Reel",
    emptyState: "Paste an Instagram link to begin.",
    enabled: false,
    comingSoon: true,
    supportsUpload: false,
    supportsPreview: false,
  },
  {
    id: "tiktok",
    name: "TikTok",
    type: "link",
    icon: "tiktok",
    placeholder: "Paste TikTok link...",
    buttonLabel: "Summarize TikTok",
    emptyState: "Paste a TikTok link to begin.",
    enabled: false,
    comingSoon: true,
    supportsUpload: false,
    supportsPreview: false,
  },
  {
    id: "x",
    name: "X (Twitter)",
    type: "link",
    icon: "x",
    placeholder: "Paste X video link...",
    buttonLabel: "Summarize X Video",
    emptyState: "Paste an X link to begin.",
    enabled: false,
    comingSoon: true,
    supportsUpload: false,
    supportsPreview: false,
  },
  {
      id: "mp3",
      name: "MP3",
      type: "audio",
      icon: "audio",
      placeholder: "Upload MP3 file...",
      buttonLabel: "Summarize Audio",
      emptyState: "Upload an audio file to begin.",
      enabled: false,
      comingSoon: true,
      supportsUpload: true,
      supportsPreview: false,
  },
  {
      id: "wav",
      name: "WAV",
      type: "audio",
      icon: "audio",
      placeholder: "Upload WAV file...",
      buttonLabel: "Summarize Audio",
      emptyState: "Upload an audio file to begin.",
      enabled: false,
      comingSoon: true,
      supportsUpload: true,
      supportsPreview: false,
  },
  {
      id: "text",
      name: "Plain Text",
      type: "text",
      icon: "text",
      placeholder: "Paste text here...",
      buttonLabel: "Summarize Text",
      emptyState: "Paste or upload text to begin.",
      enabled: false,
      comingSoon: true,
      supportsUpload: false,
      supportsPreview: false,
  },
  {
      id: "pdf",
      name: "PDF",
      type: "text",
      icon: "pdf",
      placeholder: "Upload PDF document...",
      buttonLabel: "Summarize PDF",
      emptyState: "Upload a PDF to begin.",
      enabled: false,
      comingSoon: true,
      supportsUpload: true,
      supportsPreview: false,
  }
];

export const getPlatform = (id: string) => PLATFORMS.find(p => p.id === id) || PLATFORMS[0];
export const getPlatformsByType = (type: 'link' | 'audio' | 'text') => PLATFORMS.filter(p => p.type === type);
